<?php

declare(strict_types=1);

namespace Database\Factories\Etui;

use App\Models\Etui\EtuiMod;
use App\Models\Etui\EtuiProject;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<EtuiProject>
 */
class EtuiProjectFactory extends Factory
{
    protected $model = EtuiProject::class;

    public function definition(): array
    {
        return [
            'user_id' => User::factory(),
            'mod_id' => EtuiMod::factory(),
            'name' => fake()->words(2, true),
            'content' => 'menuDef { name "'.fake()->word().'" }',
            // share_token is generated by EtuiProject::booted on create;
            // leaving it null here so the hook actually runs.
            'is_public' => false,
            'last_saved_at' => null,
            'parse_status' => 'pending',
            'parse_error_count' => 0,
            'parsed_at' => null,
        ];
    }
}
